default: &default
  adapter: postgresql
  encoding: unicode
  host: ec2-54-243-92-68.compute-1.amazonaws.com
  database: d2g2dmutfi3mtk
  pool: 5
  port: 5432
  username: jreydzfwkjxdlg
  password: 1df8bf00edbf21e7282447368e5c78b9844ed8ddda80dbd178e195fed37d86d1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
